trustPolicyExclude:
  - semver@6.3.1 # Managed by skuba
overrides:
  '@arethetypeswrong/core@0.18.2>fflate': 0.8.2 # Managed by skuba
packages:
  - packages/*
  - .

allowBuilds:
  '@ast-grep/lang-json': true # Managed by skuba
  '@ast-grep/lang-yaml': true # Managed by skuba
  '@datadog/native-appsec': true # Managed by skuba
  '@datadog/native-iast-taint-tracking': true # Managed by skuba
  '@datadog/native-metrics': true # Managed by skuba
  '@datadog/pprof': true # Managed by skuba
  dd-trace: true # Managed by skuba
  esbuild: true # Managed by skuba
  protobufjs: true # Managed by skuba
  unix-dgram: true # Managed by skuba
  unrs-resolver: true # Managed by skuba
blockExoticSubdeps: true # Managed by skuba
ignorePatchFailures: false # Managed by skuba
minimumReleaseAge: 4320 # Managed by skuba
minimumReleaseAgeExclude:
  - '@seek/*' # Managed by skuba
  - '@skuba-lib/*' # Managed by skuba
  - eslint-config-seek # Managed by skuba
  - eslint-config-skuba # Managed by skuba
  - eslint-plugin-skuba # Managed by skuba
  - pnpm-plugin-skuba # Managed by skuba
  - skuba # Managed by skuba
  - skuba-dive # Managed by skuba
  - tsconfig-seek # Managed by skuba
packageManagerStrictVersion: true # Managed by skuba
publicHoistPattern:
  - '@vitest/*' # Managed by skuba
  - vitest # Managed by skuba
  - '@arethetypeswrong/core' # Managed by skuba
  - '@eslint/*' # Managed by skuba
  - '@types*' # Managed by skuba
  - esbuild # Managed by skuba
  - eslint # Managed by skuba
  - eslint-config-skuba # Managed by skuba
  - prettier # Managed by skuba
  - publint # Managed by skuba
  - rolldown # Managed by skuba
  - tsconfig-seek # Managed by skuba
  - tsdown # Managed by skuba
  - typescript # Managed by skuba
  - '@skuba-lib/*'
strictDepBuilds: false # Managed by skuba
trustPolicy: off # Managed by skuba
