# managed by skuba
ignorePatchFailures: false
minimumReleaseAge: 4320 # 3 days
minimumReleaseAgeExclude:
  - '@seek/*'
  - '@skuba-lib/*'
  - eslint-config-seek
  - eslint-config-skuba
  - eslint-plugin-skuba
  - skuba
  - skuba-dive
  - tsconfig-seek
packageManagerStrictVersion: true
publicHoistPattern:
  - '@eslint/*'
  - '@types*'
  - eslint
  - eslint-config-skuba
  - prettier
  - esbuild
  - jest
  - tsconfig-seek
  - typescript
  # end managed by skuba

packages:
  - 'packages/*'
  - .
