openapi: 3.1.0
info:
  title: Simple API
  version: 1.0.0
  description: A simple demo for zod-openapi
  license:
    name: MIT
servers:
  - url: http://example.com/dev
    description: Dev Endpoint
  - url: http://example.com/prod
    description: Prod Endpoint
security:
  - s2sauth: []
paths:
  /job:
    get:
      operationId: getJob
      summary: Get Job
      parameters:
        - in: query
          name: id
          schema:
            $ref: "#/components/schemas/jobId"
          required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    $ref: "#/components/schemas/jobId"
                  title:
                    $ref: "#/components/schemas/jobTitle"
                  userId:
                    type: string
                    description: A unique identifier for a user
                    example: "60001234"
                required:
                  - id
                  - title
                  - userId
                description: Get Job Response
    post:
      operationId: createJob
      summary: Create Job
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  $ref: "#/components/schemas/jobTitle"
              required:
                - title
              additionalProperties: false
              description: Create Job Request
      responses:
        "201":
          description: Successful creation
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    $ref: "#/components/schemas/jobId"
                required:
                  - id
                description: Create Job Response
components:
  securitySchemes:
    s2sauth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: An s2s token issued by an allow listed consumer
  schemas:
    jobTitle:
      type: string
      minLength: 1
      description: A name that describes the job
      example: Mid level developer
    jobId:
      type: string
      format: uuid
      description: A unique identifier for a job
      example: 4dd643ff-7ec7-4666-9c88-50b7d3da34e4
