name: Validate

on:
  - pull_request
  - push

permissions: {}

jobs:
  validate:
    name: Lint & Test
    permissions:
      checks: write
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Test
        run: yarn test:ci

      - name: Lint
        run: yarn lint
